version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: worker_rabbitmq
    
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management
            - '15672:15672'
        
      
